# Generated by Django 4.0.3 on 2023-11-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dadosUsuarios',
        ),
    ]
