# Generated by Django 4.0.3 on 2023-06-07 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('valor_atual', models.IntegerField(verbose_name='valor atual')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CarteiraAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_comprado', models.IntegerField(default=0, verbose_name='valor comprado')),
                ('data', models.DateField()),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acao.acao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
