# Generated by Django 4.0.3 on 2023-06-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteiraacao',
            name='variacao_calculada',
            field=models.FloatField(blank=True, null=True, verbose_name='variação'),
        ),
        migrations.AddField(
            model_name='carteiraacao',
            name='variacao_limite',
            field=models.FloatField(blank=True, null=True, verbose_name='variação'),
        ),
    ]
