# Generated by Django 4.0.3 on 2023-09-04 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0002_carteiraacao_variacao_calculada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acao',
            name='data',
        ),
    ]
